name: "Go unit testing"

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: '1.18'

      - name: test
        run: |
          make go/test

      
      

